version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/starter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/starter/template"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/node/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/node/starter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"
