changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: CI
      labels:
        - github_actions
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
