// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tzero/v1/manage/kyc_sharing/applicant_requester.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing {
  /// <summary>
  ///* Payout-Requester-facing applicant RPCs: create an applicant, read its form pre-filled for editing, save values, submit for review, withdraw, and delete a draft. 
  /// </summary>
  public static partial class KycApplicantRequesterService
  {
    static readonly string __ServiceName = "tzero.v1.manage.kyc_sharing.KycApplicantRequesterService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_CreateRequesterKybApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_CreateRequesterKybApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_GetRequesterKybApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_GetRequesterKybApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_CreateRequesterKycApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_CreateRequesterKycApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_GetRequesterKycApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_GetRequesterKycApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest> __Marshaller_tzero_v1_manage_kyc_sharing_ListRequesterApplicantsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse> __Marshaller_tzero_v1_manage_kyc_sharing_ListRequesterApplicantsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest> __Marshaller_tzero_v1_manage_kyc_sharing_ListProviderFormsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse> __Marshaller_tzero_v1_manage_kyc_sharing_ListProviderFormsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_SaveKybApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_SaveKybApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_SaveKycApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_SaveKycApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_SubmitApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_SubmitApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_WithdrawApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_WithdrawApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest> __Marshaller_tzero_v1_manage_kyc_sharing_DeleteApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse> __Marshaller_tzero_v1_manage_kyc_sharing_DeleteApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse> __Method_CreateRequesterKybApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateRequesterKybApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_CreateRequesterKybApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_CreateRequesterKybApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse> __Method_GetRequesterKybApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRequesterKybApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_GetRequesterKybApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_GetRequesterKybApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse> __Method_CreateRequesterKycApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateRequesterKycApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_CreateRequesterKycApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_CreateRequesterKycApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse> __Method_GetRequesterKycApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRequesterKycApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_GetRequesterKycApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_GetRequesterKycApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse> __Method_ListRequesterApplicants = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListRequesterApplicants",
        __Marshaller_tzero_v1_manage_kyc_sharing_ListRequesterApplicantsRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_ListRequesterApplicantsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse> __Method_ListProviderForms = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListProviderForms",
        __Marshaller_tzero_v1_manage_kyc_sharing_ListProviderFormsRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_ListProviderFormsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse> __Method_SaveKybApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveKybApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_SaveKybApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_SaveKybApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse> __Method_SaveKycApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveKycApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_SaveKycApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_SaveKycApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse> __Method_SubmitApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SubmitApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_SubmitApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_SubmitApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse> __Method_WithdrawApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "WithdrawApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_WithdrawApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_WithdrawApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse> __Method_DeleteApplicant = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteApplicant",
        __Marshaller_tzero_v1_manage_kyc_sharing_DeleteApplicantRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_DeleteApplicantResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ApplicantRequesterReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of KycApplicantRequesterService</summary>
    [grpc::BindServiceMethod(typeof(KycApplicantRequesterService), "BindService")]
    public abstract partial class KycApplicantRequesterServiceBase
    {
      /// <summary>
      ///* Initiates a KYB applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYB form. 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse> CreateRequesterKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///* Returns the KYB form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYC applicant. 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse> GetRequesterKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///* Initiates a KYC applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYC form. 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse> CreateRequesterKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///* Returns the KYC form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYB applicant. 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse> GetRequesterKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///* Lists the calling Payout Requester's own applicants, optionally filtered by form type (KYB or KYC), Payout Provider, and/or lifecycle state. Paged: one page per call (default size 10), with `page_info.has_next` telling the caller whether to ask for the next one. 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse> ListRequesterApplicants(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///* Lists the Payout Providers the calling Payout Requester has mutual granted consent with, each with the FormType values the provider has published. Only providers with at least one published KYB or KYC form appear. 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse> ListProviderForms(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///* Stores the applicant's KYB values against the form version the client is bound to (the provider's current version on the first save), echoing the stored values for the edit UI. While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse> SaveKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///* Stores the applicant's KYC values against the form version the client is bound to (the provider's current version on the first save). While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse> SaveKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      /// Submits a draft Applicant — or resubmits a rejected one — for review, moving it to
      /// `requested`. A no-op when the Applicant is already `requested`.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse> SubmitApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      /// Withdraws an Applicant back to `draft` from `requested`, `approved`, or `rejected`,
      /// retaining its field values. A no-op when already `draft`.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse> WithdrawApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      /// Deletes a `draft` or `rejected` Applicant, freeing its identity for a fresh Applicant for the same
      /// customer and provider; from `requested` or `approved`, withdraw to `draft` first.
      /// Provider-side review transitions (approve/reject) live on KycApplicantProviderService.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse> DeleteApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for KycApplicantRequesterService</summary>
    public partial class KycApplicantRequesterServiceClient : grpc::ClientBase<KycApplicantRequesterServiceClient>
    {
      /// <summary>Creates a new client for KycApplicantRequesterService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public KycApplicantRequesterServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for KycApplicantRequesterService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public KycApplicantRequesterServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected KycApplicantRequesterServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected KycApplicantRequesterServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///* Initiates a KYB applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYB form. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse CreateRequesterKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRequesterKybApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Initiates a KYB applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYB form. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse CreateRequesterKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateRequesterKybApplicant, null, options, request);
      }
      /// <summary>
      ///* Initiates a KYB applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYB form. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse> CreateRequesterKybApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRequesterKybApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Initiates a KYB applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYB form. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse> CreateRequesterKybApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateRequesterKybApplicant, null, options, request);
      }
      /// <summary>
      ///* Returns the KYB form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYC applicant. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse GetRequesterKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRequesterKybApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Returns the KYB form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYC applicant. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse GetRequesterKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRequesterKybApplicant, null, options, request);
      }
      /// <summary>
      ///* Returns the KYB form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYC applicant. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse> GetRequesterKybApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRequesterKybApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Returns the KYB form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYC applicant. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse> GetRequesterKybApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRequesterKybApplicant, null, options, request);
      }
      /// <summary>
      ///* Initiates a KYC applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYC form. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse CreateRequesterKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRequesterKycApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Initiates a KYC applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYC form. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse CreateRequesterKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateRequesterKycApplicant, null, options, request);
      }
      /// <summary>
      ///* Initiates a KYC applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYC form. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse> CreateRequesterKycApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRequesterKycApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Initiates a KYC applicant by binding a fresh draft to the payout provider's current form version. A repeat call for an already-created applicant returns AlreadyExists, and FailedPrecondition when the provider has no published KYC form. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse> CreateRequesterKycApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateRequesterKycApplicant, null, options, request);
      }
      /// <summary>
      ///* Returns the KYC form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYB applicant. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse GetRequesterKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRequesterKycApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Returns the KYC form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYB applicant. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse GetRequesterKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRequesterKycApplicant, null, options, request);
      }
      /// <summary>
      ///* Returns the KYC form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYB applicant. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse> GetRequesterKycApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRequesterKycApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Returns the KYC form at the version the applicant is bound to plus their stored values, for editing. Read-only: FailedPrecondition when the applicant does not exist — create it first — and InvalidArgument when the `client_id` has a KYB applicant. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse> GetRequesterKycApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRequesterKycApplicant, null, options, request);
      }
      /// <summary>
      ///* Lists the calling Payout Requester's own applicants, optionally filtered by form type (KYB or KYC), Payout Provider, and/or lifecycle state. Paged: one page per call (default size 10), with `page_info.has_next` telling the caller whether to ask for the next one. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse ListRequesterApplicants(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListRequesterApplicants(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Lists the calling Payout Requester's own applicants, optionally filtered by form type (KYB or KYC), Payout Provider, and/or lifecycle state. Paged: one page per call (default size 10), with `page_info.has_next` telling the caller whether to ask for the next one. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse ListRequesterApplicants(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListRequesterApplicants, null, options, request);
      }
      /// <summary>
      ///* Lists the calling Payout Requester's own applicants, optionally filtered by form type (KYB or KYC), Payout Provider, and/or lifecycle state. Paged: one page per call (default size 10), with `page_info.has_next` telling the caller whether to ask for the next one. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse> ListRequesterApplicantsAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListRequesterApplicantsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Lists the calling Payout Requester's own applicants, optionally filtered by form type (KYB or KYC), Payout Provider, and/or lifecycle state. Paged: one page per call (default size 10), with `page_info.has_next` telling the caller whether to ask for the next one. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse> ListRequesterApplicantsAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListRequesterApplicants, null, options, request);
      }
      /// <summary>
      ///* Lists the Payout Providers the calling Payout Requester has mutual granted consent with, each with the FormType values the provider has published. Only providers with at least one published KYB or KYC form appear. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse ListProviderForms(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListProviderForms(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Lists the Payout Providers the calling Payout Requester has mutual granted consent with, each with the FormType values the provider has published. Only providers with at least one published KYB or KYC form appear. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse ListProviderForms(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListProviderForms, null, options, request);
      }
      /// <summary>
      ///* Lists the Payout Providers the calling Payout Requester has mutual granted consent with, each with the FormType values the provider has published. Only providers with at least one published KYB or KYC form appear. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse> ListProviderFormsAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListProviderFormsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Lists the Payout Providers the calling Payout Requester has mutual granted consent with, each with the FormType values the provider has published. Only providers with at least one published KYB or KYC form appear. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse> ListProviderFormsAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListProviderForms, null, options, request);
      }
      /// <summary>
      ///* Stores the applicant's KYB values against the form version the client is bound to (the provider's current version on the first save), echoing the stored values for the edit UI. While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse SaveKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveKybApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Stores the applicant's KYB values against the form version the client is bound to (the provider's current version on the first save), echoing the stored values for the edit UI. While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse SaveKybApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveKybApplicant, null, options, request);
      }
      /// <summary>
      ///* Stores the applicant's KYB values against the form version the client is bound to (the provider's current version on the first save), echoing the stored values for the edit UI. While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse> SaveKybApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveKybApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Stores the applicant's KYB values against the form version the client is bound to (the provider's current version on the first save), echoing the stored values for the edit UI. While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse> SaveKybApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveKybApplicant, null, options, request);
      }
      /// <summary>
      ///* Stores the applicant's KYC values against the form version the client is bound to (the provider's current version on the first save). While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse SaveKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveKycApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Stores the applicant's KYC values against the form version the client is bound to (the provider's current version on the first save). While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse SaveKycApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveKycApplicant, null, options, request);
      }
      /// <summary>
      ///* Stores the applicant's KYC values against the form version the client is bound to (the provider's current version on the first save). While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse> SaveKycApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveKycApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///* Stores the applicant's KYC values against the form version the client is bound to (the provider's current version on the first save). While the applicant is rejected, the values must fill every field its form requires; to save partial progress, withdraw it to draft first. 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse> SaveKycApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveKycApplicant, null, options, request);
      }
      /// <summary>
      ///*
      /// Submits a draft Applicant — or resubmits a rejected one — for review, moving it to
      /// `requested`. A no-op when the Applicant is already `requested`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse SubmitApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubmitApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Submits a draft Applicant — or resubmits a rejected one — for review, moving it to
      /// `requested`. A no-op when the Applicant is already `requested`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse SubmitApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SubmitApplicant, null, options, request);
      }
      /// <summary>
      ///*
      /// Submits a draft Applicant — or resubmits a rejected one — for review, moving it to
      /// `requested`. A no-op when the Applicant is already `requested`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse> SubmitApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubmitApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Submits a draft Applicant — or resubmits a rejected one — for review, moving it to
      /// `requested`. A no-op when the Applicant is already `requested`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse> SubmitApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SubmitApplicant, null, options, request);
      }
      /// <summary>
      ///*
      /// Withdraws an Applicant back to `draft` from `requested`, `approved`, or `rejected`,
      /// retaining its field values. A no-op when already `draft`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse WithdrawApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WithdrawApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Withdraws an Applicant back to `draft` from `requested`, `approved`, or `rejected`,
      /// retaining its field values. A no-op when already `draft`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse WithdrawApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_WithdrawApplicant, null, options, request);
      }
      /// <summary>
      ///*
      /// Withdraws an Applicant back to `draft` from `requested`, `approved`, or `rejected`,
      /// retaining its field values. A no-op when already `draft`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse> WithdrawApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WithdrawApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Withdraws an Applicant back to `draft` from `requested`, `approved`, or `rejected`,
      /// retaining its field values. A no-op when already `draft`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse> WithdrawApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_WithdrawApplicant, null, options, request);
      }
      /// <summary>
      ///*
      /// Deletes a `draft` or `rejected` Applicant, freeing its identity for a fresh Applicant for the same
      /// customer and provider; from `requested` or `approved`, withdraw to `draft` first.
      /// Provider-side review transitions (approve/reject) live on KycApplicantProviderService.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse DeleteApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Deletes a `draft` or `rejected` Applicant, freeing its identity for a fresh Applicant for the same
      /// customer and provider; from `requested` or `approved`, withdraw to `draft` first.
      /// Provider-side review transitions (approve/reject) live on KycApplicantProviderService.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse DeleteApplicant(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteApplicant, null, options, request);
      }
      /// <summary>
      ///*
      /// Deletes a `draft` or `rejected` Applicant, freeing its identity for a fresh Applicant for the same
      /// customer and provider; from `requested` or `approved`, withdraw to `draft` first.
      /// Provider-side review transitions (approve/reject) live on KycApplicantProviderService.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse> DeleteApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Deletes a `draft` or `rejected` Applicant, freeing its identity for a fresh Applicant for the same
      /// customer and provider; from `requested` or `approved`, withdraw to `draft` first.
      /// Provider-side review transitions (approve/reject) live on KycApplicantProviderService.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse> DeleteApplicantAsync(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteApplicant, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override KycApplicantRequesterServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new KycApplicantRequesterServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(KycApplicantRequesterServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateRequesterKybApplicant, serviceImpl.CreateRequesterKybApplicant)
          .AddMethod(__Method_GetRequesterKybApplicant, serviceImpl.GetRequesterKybApplicant)
          .AddMethod(__Method_CreateRequesterKycApplicant, serviceImpl.CreateRequesterKycApplicant)
          .AddMethod(__Method_GetRequesterKycApplicant, serviceImpl.GetRequesterKycApplicant)
          .AddMethod(__Method_ListRequesterApplicants, serviceImpl.ListRequesterApplicants)
          .AddMethod(__Method_ListProviderForms, serviceImpl.ListProviderForms)
          .AddMethod(__Method_SaveKybApplicant, serviceImpl.SaveKybApplicant)
          .AddMethod(__Method_SaveKycApplicant, serviceImpl.SaveKycApplicant)
          .AddMethod(__Method_SubmitApplicant, serviceImpl.SubmitApplicant)
          .AddMethod(__Method_WithdrawApplicant, serviceImpl.WithdrawApplicant)
          .AddMethod(__Method_DeleteApplicant, serviceImpl.DeleteApplicant).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, KycApplicantRequesterServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateRequesterKybApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKybApplicantResponse>(serviceImpl.CreateRequesterKybApplicant));
      serviceBinder.AddMethod(__Method_GetRequesterKybApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKybApplicantResponse>(serviceImpl.GetRequesterKybApplicant));
      serviceBinder.AddMethod(__Method_CreateRequesterKycApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.CreateRequesterKycApplicantResponse>(serviceImpl.CreateRequesterKycApplicant));
      serviceBinder.AddMethod(__Method_GetRequesterKycApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.GetRequesterKycApplicantResponse>(serviceImpl.GetRequesterKycApplicant));
      serviceBinder.AddMethod(__Method_ListRequesterApplicants, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListRequesterApplicantsResponse>(serviceImpl.ListRequesterApplicants));
      serviceBinder.AddMethod(__Method_ListProviderForms, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.ListProviderFormsResponse>(serviceImpl.ListProviderForms));
      serviceBinder.AddMethod(__Method_SaveKybApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKybApplicantResponse>(serviceImpl.SaveKybApplicant));
      serviceBinder.AddMethod(__Method_SaveKycApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SaveKycApplicantResponse>(serviceImpl.SaveKycApplicant));
      serviceBinder.AddMethod(__Method_SubmitApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.SubmitApplicantResponse>(serviceImpl.SubmitApplicant));
      serviceBinder.AddMethod(__Method_WithdrawApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.WithdrawApplicantResponse>(serviceImpl.WithdrawApplicant));
      serviceBinder.AddMethod(__Method_DeleteApplicant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DeleteApplicantResponse>(serviceImpl.DeleteApplicant));
    }

  }
}
#endregion
