// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tzero/v1/manage/kyc_sharing/file.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing {
  /// <summary>
  ///*
  /// File storage for KYB/KYC sharing forms: a Payout Requester uploads a file (a
  /// PDF or image) for one of its customers against a Payout Provider's form and
  /// receives a stable file id to reference it; both sides can download it later.
  /// </summary>
  public static partial class KycFileService
  {
    static readonly string __ServiceName = "tzero.v1.manage.kyc_sharing.KycFileService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileRequest> __Marshaller_tzero_v1_manage_kyc_sharing_UploadFileRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileResponse> __Marshaller_tzero_v1_manage_kyc_sharing_UploadFileResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileRequest> __Marshaller_tzero_v1_manage_kyc_sharing_DownloadFileRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileResponse> __Marshaller_tzero_v1_manage_kyc_sharing_DownloadFileResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileResponse> __Method_UploadFile = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "UploadFile",
        __Marshaller_tzero_v1_manage_kyc_sharing_UploadFileRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_UploadFileResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileResponse> __Method_DownloadFile = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "DownloadFile",
        __Marshaller_tzero_v1_manage_kyc_sharing_DownloadFileRequest,
        __Marshaller_tzero_v1_manage_kyc_sharing_DownloadFileResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.FileReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of KycFileService</summary>
    [grpc::BindServiceMethod(typeof(KycFileService), "BindService")]
    public abstract partial class KycFileServiceBase
    {
      /// <summary>
      ///*
      /// Client-streaming upload (first message Metadata, then Chunks) that stores the
      /// file and returns its id. A retry with the same optional Metadata.upload_id
      /// returns the originally stored file; without it, each call stores a new file.
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileResponse> UploadFile(grpc::IAsyncStreamReader<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      /// Server-streaming download of a previously uploaded file. The first response
      /// message carries Metadata (content type, advisory original name); the rest are
      /// Chunks of the file bytes. The file is identified by its id plus the (Payout
      /// Requester, Payout Provider, client) tuple it must belong to; access is granted
      /// to the owning requester (any state) and to the provider once the matching
      /// application is past draft.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task DownloadFile(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileRequest request, grpc::IServerStreamWriter<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for KycFileService</summary>
    public partial class KycFileServiceClient : grpc::ClientBase<KycFileServiceClient>
    {
      /// <summary>Creates a new client for KycFileService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public KycFileServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for KycFileService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public KycFileServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected KycFileServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected KycFileServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///*
      /// Client-streaming upload (first message Metadata, then Chunks) that stores the
      /// file and returns its id. A retry with the same optional Metadata.upload_id
      /// returns the originally stored file; without it, each call stores a new file.
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileResponse> UploadFile(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadFile(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Client-streaming upload (first message Metadata, then Chunks) that stores the
      /// file and returns its id. A retry with the same optional Metadata.upload_id
      /// returns the originally stored file; without it, each call stores a new file.
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileResponse> UploadFile(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_UploadFile, null, options);
      }
      /// <summary>
      ///*
      /// Server-streaming download of a previously uploaded file. The first response
      /// message carries Metadata (content type, advisory original name); the rest are
      /// Chunks of the file bytes. The file is identified by its id plus the (Payout
      /// Requester, Payout Provider, client) tuple it must belong to; access is granted
      /// to the owning requester (any state) and to the provider once the matching
      /// application is past draft.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileResponse> DownloadFile(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DownloadFile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Server-streaming download of a previously uploaded file. The first response
      /// message carries Metadata (content type, advisory original name); the rest are
      /// Chunks of the file bytes. The file is identified by its id plus the (Payout
      /// Requester, Payout Provider, client) tuple it must belong to; access is granted
      /// to the owning requester (any state) and to the provider once the matching
      /// application is past draft.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileResponse> DownloadFile(global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_DownloadFile, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override KycFileServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new KycFileServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(KycFileServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_UploadFile, serviceImpl.UploadFile)
          .AddMethod(__Method_DownloadFile, serviceImpl.DownloadFile).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, KycFileServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_UploadFile, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.UploadFileResponse>(serviceImpl.UploadFile));
      serviceBinder.AddMethod(__Method_DownloadFile, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileRequest, global::T0.ProviderSdk.Api.Tzero.V1.Manage.KycSharing.DownloadFileResponse>(serviceImpl.DownloadFile));
    }

  }
}
#endregion
