// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tzero/v1/manage/kyc_sharing/form_setup.proto

package kyc_sharingconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	kyc_sharing "github.com/t-0-network/provider-sdk/go/api/tzero/v1/manage/kyc_sharing"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// KycFormSetupServiceName is the fully-qualified name of the KycFormSetupService service.
	KycFormSetupServiceName = "tzero.v1.manage.kyc_sharing.KycFormSetupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// KycFormSetupServiceSaveKybFormProcedure is the fully-qualified name of the KycFormSetupService's
	// SaveKybForm RPC.
	KycFormSetupServiceSaveKybFormProcedure = "/tzero.v1.manage.kyc_sharing.KycFormSetupService/SaveKybForm"
	// KycFormSetupServiceSaveKycFormProcedure is the fully-qualified name of the KycFormSetupService's
	// SaveKycForm RPC.
	KycFormSetupServiceSaveKycFormProcedure = "/tzero.v1.manage.kyc_sharing.KycFormSetupService/SaveKycForm"
	// KycFormSetupServiceGetFormsProcedure is the fully-qualified name of the KycFormSetupService's
	// GetForms RPC.
	KycFormSetupServiceGetFormsProcedure = "/tzero.v1.manage.kyc_sharing.KycFormSetupService/GetForms"
)

// KycFormSetupServiceClient is a client for the tzero.v1.manage.kyc_sharing.KycFormSetupService
// service.
type KycFormSetupServiceClient interface {
	// *
	// Full-definition replace of the KYB Form. The network
	// picks no-op / in-place update / fork / first version.
	SaveKybForm(context.Context, *connect.Request[kyc_sharing.SaveKybFormRequest]) (*connect.Response[kyc_sharing.SaveKybFormResponse], error)
	// *
	// Full-definition replace of the KYC Form. Same
	// no-op / in-place / fork / first-version branching as SaveKybForm.
	SaveKycForm(context.Context, *connect.Request[kyc_sharing.SaveKycFormRequest]) (*connect.Response[kyc_sharing.SaveKycFormResponse], error)
	// *
	// Returns the authenticated Payout Provider's current KYB and KYC forms, each
	// at its latest version. A form type with no published form is returned absent.
	GetForms(context.Context, *connect.Request[kyc_sharing.GetFormsRequest]) (*connect.Response[kyc_sharing.GetFormsResponse], error)
}

// NewKycFormSetupServiceClient constructs a client for the
// tzero.v1.manage.kyc_sharing.KycFormSetupService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKycFormSetupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) KycFormSetupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	kycFormSetupServiceMethods := kyc_sharing.File_tzero_v1_manage_kyc_sharing_form_setup_proto.Services().ByName("KycFormSetupService").Methods()
	return &kycFormSetupServiceClient{
		saveKybForm: connect.NewClient[kyc_sharing.SaveKybFormRequest, kyc_sharing.SaveKybFormResponse](
			httpClient,
			baseURL+KycFormSetupServiceSaveKybFormProcedure,
			connect.WithSchema(kycFormSetupServiceMethods.ByName("SaveKybForm")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		saveKycForm: connect.NewClient[kyc_sharing.SaveKycFormRequest, kyc_sharing.SaveKycFormResponse](
			httpClient,
			baseURL+KycFormSetupServiceSaveKycFormProcedure,
			connect.WithSchema(kycFormSetupServiceMethods.ByName("SaveKycForm")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		getForms: connect.NewClient[kyc_sharing.GetFormsRequest, kyc_sharing.GetFormsResponse](
			httpClient,
			baseURL+KycFormSetupServiceGetFormsProcedure,
			connect.WithSchema(kycFormSetupServiceMethods.ByName("GetForms")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// kycFormSetupServiceClient implements KycFormSetupServiceClient.
type kycFormSetupServiceClient struct {
	saveKybForm *connect.Client[kyc_sharing.SaveKybFormRequest, kyc_sharing.SaveKybFormResponse]
	saveKycForm *connect.Client[kyc_sharing.SaveKycFormRequest, kyc_sharing.SaveKycFormResponse]
	getForms    *connect.Client[kyc_sharing.GetFormsRequest, kyc_sharing.GetFormsResponse]
}

// SaveKybForm calls tzero.v1.manage.kyc_sharing.KycFormSetupService.SaveKybForm.
func (c *kycFormSetupServiceClient) SaveKybForm(ctx context.Context, req *connect.Request[kyc_sharing.SaveKybFormRequest]) (*connect.Response[kyc_sharing.SaveKybFormResponse], error) {
	return c.saveKybForm.CallUnary(ctx, req)
}

// SaveKycForm calls tzero.v1.manage.kyc_sharing.KycFormSetupService.SaveKycForm.
func (c *kycFormSetupServiceClient) SaveKycForm(ctx context.Context, req *connect.Request[kyc_sharing.SaveKycFormRequest]) (*connect.Response[kyc_sharing.SaveKycFormResponse], error) {
	return c.saveKycForm.CallUnary(ctx, req)
}

// GetForms calls tzero.v1.manage.kyc_sharing.KycFormSetupService.GetForms.
func (c *kycFormSetupServiceClient) GetForms(ctx context.Context, req *connect.Request[kyc_sharing.GetFormsRequest]) (*connect.Response[kyc_sharing.GetFormsResponse], error) {
	return c.getForms.CallUnary(ctx, req)
}

// KycFormSetupServiceHandler is an implementation of the
// tzero.v1.manage.kyc_sharing.KycFormSetupService service.
type KycFormSetupServiceHandler interface {
	// *
	// Full-definition replace of the KYB Form. The network
	// picks no-op / in-place update / fork / first version.
	SaveKybForm(context.Context, *connect.Request[kyc_sharing.SaveKybFormRequest]) (*connect.Response[kyc_sharing.SaveKybFormResponse], error)
	// *
	// Full-definition replace of the KYC Form. Same
	// no-op / in-place / fork / first-version branching as SaveKybForm.
	SaveKycForm(context.Context, *connect.Request[kyc_sharing.SaveKycFormRequest]) (*connect.Response[kyc_sharing.SaveKycFormResponse], error)
	// *
	// Returns the authenticated Payout Provider's current KYB and KYC forms, each
	// at its latest version. A form type with no published form is returned absent.
	GetForms(context.Context, *connect.Request[kyc_sharing.GetFormsRequest]) (*connect.Response[kyc_sharing.GetFormsResponse], error)
}

// NewKycFormSetupServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKycFormSetupServiceHandler(svc KycFormSetupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	kycFormSetupServiceMethods := kyc_sharing.File_tzero_v1_manage_kyc_sharing_form_setup_proto.Services().ByName("KycFormSetupService").Methods()
	kycFormSetupServiceSaveKybFormHandler := connect.NewUnaryHandler(
		KycFormSetupServiceSaveKybFormProcedure,
		svc.SaveKybForm,
		connect.WithSchema(kycFormSetupServiceMethods.ByName("SaveKybForm")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	kycFormSetupServiceSaveKycFormHandler := connect.NewUnaryHandler(
		KycFormSetupServiceSaveKycFormProcedure,
		svc.SaveKycForm,
		connect.WithSchema(kycFormSetupServiceMethods.ByName("SaveKycForm")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	kycFormSetupServiceGetFormsHandler := connect.NewUnaryHandler(
		KycFormSetupServiceGetFormsProcedure,
		svc.GetForms,
		connect.WithSchema(kycFormSetupServiceMethods.ByName("GetForms")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/tzero.v1.manage.kyc_sharing.KycFormSetupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case KycFormSetupServiceSaveKybFormProcedure:
			kycFormSetupServiceSaveKybFormHandler.ServeHTTP(w, r)
		case KycFormSetupServiceSaveKycFormProcedure:
			kycFormSetupServiceSaveKycFormHandler.ServeHTTP(w, r)
		case KycFormSetupServiceGetFormsProcedure:
			kycFormSetupServiceGetFormsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedKycFormSetupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedKycFormSetupServiceHandler struct{}

func (UnimplementedKycFormSetupServiceHandler) SaveKybForm(context.Context, *connect.Request[kyc_sharing.SaveKybFormRequest]) (*connect.Response[kyc_sharing.SaveKybFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.manage.kyc_sharing.KycFormSetupService.SaveKybForm is not implemented"))
}

func (UnimplementedKycFormSetupServiceHandler) SaveKycForm(context.Context, *connect.Request[kyc_sharing.SaveKycFormRequest]) (*connect.Response[kyc_sharing.SaveKycFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.manage.kyc_sharing.KycFormSetupService.SaveKycForm is not implemented"))
}

func (UnimplementedKycFormSetupServiceHandler) GetForms(context.Context, *connect.Request[kyc_sharing.GetFormsRequest]) (*connect.Response[kyc_sharing.GetFormsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tzero.v1.manage.kyc_sharing.KycFormSetupService.GetForms is not implemented"))
}
