# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: tzero/v1/system/system.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import tzero.v1.system.system_pb2 as tzero_dot_v1_dot_system_dot_system__pb2


class SystemService(Protocol):
    async def health(self, request: tzero_dot_v1_dot_system_dot_system__pb2.HealthRequest, ctx: RequestContext) -> tzero_dot_v1_dot_system_dot_system__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SystemServiceASGIApplication(ConnectASGIApplication[SystemService]):
    def __init__(self, service: SystemService | AsyncGenerator[SystemService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.system.SystemService/Health": Endpoint.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="tzero.v1.system.SystemService",
                        input=tzero_dot_v1_dot_system_dot_system__pb2.HealthRequest,
                        output=tzero_dot_v1_dot_system_dot_system__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.health,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.system.SystemService"


class SystemServiceClient(ConnectClient):
    async def health(
        self,
        request: tzero_dot_v1_dot_system_dot_system__pb2.HealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> tzero_dot_v1_dot_system_dot_system__pb2.HealthResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="tzero.v1.system.SystemService",
                input=tzero_dot_v1_dot_system_dot_system__pb2.HealthRequest,
                output=tzero_dot_v1_dot_system_dot_system__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )





class SystemServiceSync(Protocol):
    def health(self, request: tzero_dot_v1_dot_system_dot_system__pb2.HealthRequest, ctx: RequestContext) -> tzero_dot_v1_dot_system_dot_system__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SystemServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SystemServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.system.SystemService/Health": EndpointSync.unary(
                    method=MethodInfo(
                        name="Health",
                        service_name="tzero.v1.system.SystemService",
                        input=tzero_dot_v1_dot_system_dot_system__pb2.HealthRequest,
                        output=tzero_dot_v1_dot_system_dot_system__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.health,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.system.SystemService"


class SystemServiceClientSync(ConnectClientSync):
    def health(
        self,
        request: tzero_dot_v1_dot_system_dot_system__pb2.HealthRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> tzero_dot_v1_dot_system_dot_system__pb2.HealthResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Health",
                service_name="tzero.v1.system.SystemService",
                input=tzero_dot_v1_dot_system_dot_system__pb2.HealthRequest,
                output=tzero_dot_v1_dot_system_dot_system__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )


