# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tzero/v1/system/system.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tzero/v1/system/system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctzero/v1/system/system.proto\x12\x0ftzero.v1.system\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x62uf/validate/validate.proto\"\x0f\n\rHealthRequest\"\xd9\x01\n\x0eHealthResponse\x12\x1a\n\x08services\x18\n \x03(\tR\x08services\x12=\n\x0c\x63urrent_time\x18\x14 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0b\x63urrentTime\x12(\n\x0bsdk_version\x18\x1e \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\nsdkVersion\x12\x42\n\rsdk_ecosystem\x18( \x01(\x0e\x32\x1d.tzero.v1.system.SdkEcosystemR\x0csdkEcosystem*\xa7\x01\n\x0cSdkEcosystem\x12\x1d\n\x19SDK_ECOSYSTEM_UNSPECIFIED\x10\x00\x12\x14\n\x10SDK_ECOSYSTEM_GO\x10\x01\x12\x16\n\x12SDK_ECOSYSTEM_NODE\x10\x02\x12\x18\n\x14SDK_ECOSYSTEM_PYTHON\x10\x03\x12\x16\n\x12SDK_ECOSYSTEM_JAVA\x10\x04\x12\x18\n\x14SDK_ECOSYSTEM_CSHARP\x10\x05\x32_\n\rSystemService\x12N\n\x06Health\x12\x1e.tzero.v1.system.HealthRequest\x1a\x1f.tzero.v1.system.HealthResponse\"\x03\x90\x02\x01\x42\xcf\x01\n\x13\x63om.tzero.v1.systemB\x0bSystemProtoP\x01Z:github.com/t-0-network/provider-sdk/go/api/tzero/v1/system\xa2\x02\x03TVS\xaa\x02\"T0.ProviderSdk.Api.Tzero.V1.System\xca\x02\x0fTzero\\V1\\System\xe2\x02\x1bTzero\\V1\\System\\GPBMetadata\xea\x02\x11Tzero::V1::Systemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tzero.v1.system.system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.tzero.v1.systemB\013SystemProtoP\001Z:github.com/t-0-network/provider-sdk/go/api/tzero/v1/system\242\002\003TVS\252\002\"T0.ProviderSdk.Api.Tzero.V1.System\312\002\017Tzero\\V1\\System\342\002\033Tzero\\V1\\System\\GPBMetadata\352\002\021Tzero::V1::System'
  _globals['_HEALTHRESPONSE'].fields_by_name['sdk_version']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['sdk_version']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_SYSTEMSERVICE'].methods_by_name['Health']._loaded_options = None
  _globals['_SYSTEMSERVICE'].methods_by_name['Health']._serialized_options = b'\220\002\001'
  _globals['_SDKECOSYSTEM']._serialized_start=349
  _globals['_SDKECOSYSTEM']._serialized_end=516
  _globals['_HEALTHREQUEST']._serialized_start=111
  _globals['_HEALTHREQUEST']._serialized_end=126
  _globals['_HEALTHRESPONSE']._serialized_start=129
  _globals['_HEALTHRESPONSE']._serialized_end=346
  _globals['_SYSTEMSERVICE']._serialized_start=518
  _globals['_SYSTEMSERVICE']._serialized_end=613
# @@protoc_insertion_point(module_scope)
