<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>{{PROJECT_NAME_PASCAL}}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="T0.ProviderSdk" Version="1.1.31" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
  </ItemGroup>

</Project>
