# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tzero/v1/payment_intent/beneficiary.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'tzero/v1/payment_intent/beneficiary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tzero.v1.common import common_pb2 as tzero_dot_v1_dot_common_dot_common__pb2
from tzero.v1.common import payment_method_pb2 as tzero_dot_v1_dot_common_dot_payment__method__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)tzero/v1/payment_intent/beneficiary.proto\x12\x17tzero.v1.payment_intent\x1a\x1ctzero/v1/common/common.proto\x1a$tzero/v1/common/payment_method.proto\x1a\x1b\x62uf/validate/validate.proto\"\x8f\x04\n\x1aPaymentIntentUpdateRequest\x12\x33\n\x11payment_intent_id\x18\n \x01(\x04\x42\x07\xbaH\x04\x32\x02 \x00R\x0fpaymentIntentId\x12j\n\x0e\x66unds_received\x18\x14 \x01(\x0b\x32\x41.tzero.v1.payment_intent.PaymentIntentUpdateRequest.FundsReceivedH\x00R\rfundsReceived\x1a\xc5\x02\n\rFundsReceived\x12\x45\n\x11settlement_amount\x18\n \x01(\x0b\x32\x18.tzero.v1.common.DecimalR\x10settlementAmount\x12,\n\x04rate\x18\x14 \x01(\x0b\x32\x18.tzero.v1.common.DecimalR\x04rate\x12?\n\x0epayment_amount\x18\x1e \x01(\x0b\x32\x18.tzero.v1.common.DecimalR\rpaymentAmount\x12I\n\x0epayment_method\x18( \x01(\x0e\x32\".tzero.v1.common.PaymentMethodTypeR\rpaymentMethod\x12\x33\n\x15transaction_reference\x18\x32 \x01(\tR\x14transactionReferenceB\x08\n\x06update\"\x1d\n\x1bPaymentIntentUpdateResponse2\x9c\x01\n\x12\x42\x65neficiaryService\x12\x85\x01\n\x13PaymentIntentUpdate\x12\x33.tzero.v1.payment_intent.PaymentIntentUpdateRequest\x1a\x34.tzero.v1.payment_intent.PaymentIntentUpdateResponse\"\x03\x90\x02\x02\x42\xfe\x01\n,network.t0.sdk.proto.tzero.v1.payment_intentB\x10\x42\x65neficiaryProtoP\x01ZBgithub.com/t-0-network/provider-sdk/go/api/tzero/v1/payment_intent\xa2\x02\x03TVP\xaa\x02\x16Tzero.V1.PaymentIntent\xca\x02\x16Tzero\\V1\\PaymentIntent\xe2\x02\"Tzero\\V1\\PaymentIntent\\GPBMetadata\xea\x02\x18Tzero::V1::PaymentIntentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tzero.v1.payment_intent.beneficiary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,network.t0.sdk.proto.tzero.v1.payment_intentB\020BeneficiaryProtoP\001ZBgithub.com/t-0-network/provider-sdk/go/api/tzero/v1/payment_intent\242\002\003TVP\252\002\026Tzero.V1.PaymentIntent\312\002\026Tzero\\V1\\PaymentIntent\342\002\"Tzero\\V1\\PaymentIntent\\GPBMetadata\352\002\030Tzero::V1::PaymentIntent'
  _globals['_PAYMENTINTENTUPDATEREQUEST'].fields_by_name['payment_intent_id']._loaded_options = None
  _globals['_PAYMENTINTENTUPDATEREQUEST'].fields_by_name['payment_intent_id']._serialized_options = b'\272H\0042\002 \000'
  _globals['_BENEFICIARYSERVICE'].methods_by_name['PaymentIntentUpdate']._loaded_options = None
  _globals['_BENEFICIARYSERVICE'].methods_by_name['PaymentIntentUpdate']._serialized_options = b'\220\002\002'
  _globals['_PAYMENTINTENTUPDATEREQUEST']._serialized_start=168
  _globals['_PAYMENTINTENTUPDATEREQUEST']._serialized_end=695
  _globals['_PAYMENTINTENTUPDATEREQUEST_FUNDSRECEIVED']._serialized_start=360
  _globals['_PAYMENTINTENTUPDATEREQUEST_FUNDSRECEIVED']._serialized_end=685
  _globals['_PAYMENTINTENTUPDATERESPONSE']._serialized_start=697
  _globals['_PAYMENTINTENTUPDATERESPONSE']._serialized_end=726
  _globals['_BENEFICIARYSERVICE']._serialized_start=729
  _globals['_BENEFICIARYSERVICE']._serialized_end=885
# @@protoc_insertion_point(module_scope)
