// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tzero/v1/system/system.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace T0.ProviderSdk.Api.Tzero.V1.System {
  /// <summary>
  ///*
  /// SystemService exposes operational/introspection RPCs on a provider
  /// endpoint. It is automatically registered by every provider SDK;
  /// customers do not implement it themselves. Calls are signed with the
  /// T-0 Network keypair, just like every other provider RPC.
  ///
  /// Health() is the first RPC. Future operational endpoints (e.g.
  /// Diagnostics, BuildInfo) belong on this service so customers continue
  /// to get them automatically as they upgrade the SDK.
  /// </summary>
  public static partial class SystemService
  {
    static readonly string __ServiceName = "tzero.v1.system.SystemService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest> __Marshaller_tzero_v1_system_HealthRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse> __Marshaller_tzero_v1_system_HealthResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest, global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse> __Method_Health = new grpc::Method<global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest, global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Health",
        __Marshaller_tzero_v1_system_HealthRequest,
        __Marshaller_tzero_v1_system_HealthResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::T0.ProviderSdk.Api.Tzero.V1.System.SystemReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SystemService</summary>
    [grpc::BindServiceMethod(typeof(SystemService), "BindService")]
    public abstract partial class SystemServiceBase
    {
      /// <summary>
      ///*
      /// Health returns the list of RPC services registered on this provider,
      /// the server's current wall-clock time, and the SDK build identifying
      /// this deployment. The returned `services` list always includes
      /// "tzero.v1.system.SystemService" itself.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse> Health(global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SystemService</summary>
    public partial class SystemServiceClient : grpc::ClientBase<SystemServiceClient>
    {
      /// <summary>Creates a new client for SystemService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SystemServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SystemService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SystemServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SystemServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SystemServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///*
      /// Health returns the list of RPC services registered on this provider,
      /// the server's current wall-clock time, and the SDK build identifying
      /// this deployment. The returned `services` list always includes
      /// "tzero.v1.system.SystemService" itself.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse Health(global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Health(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Health returns the list of RPC services registered on this provider,
      /// the server's current wall-clock time, and the SDK build identifying
      /// this deployment. The returned `services` list always includes
      /// "tzero.v1.system.SystemService" itself.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse Health(global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Health, null, options, request);
      }
      /// <summary>
      ///*
      /// Health returns the list of RPC services registered on this provider,
      /// the server's current wall-clock time, and the SDK build identifying
      /// this deployment. The returned `services` list always includes
      /// "tzero.v1.system.SystemService" itself.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse> HealthAsync(global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HealthAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Health returns the list of RPC services registered on this provider,
      /// the server's current wall-clock time, and the SDK build identifying
      /// this deployment. The returned `services` list always includes
      /// "tzero.v1.system.SystemService" itself.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse> HealthAsync(global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Health, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SystemServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SystemServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(SystemServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Health, serviceImpl.Health).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SystemServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Health, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::T0.ProviderSdk.Api.Tzero.V1.System.HealthRequest, global::T0.ProviderSdk.Api.Tzero.V1.System.HealthResponse>(serviceImpl.Health));
    }

  }
}
#endregion
