# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: tzero/v1/payment/network.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import tzero.v1.payment.network_pb2 as tzero_dot_v1_dot_payment_dot_network__pb2


class NetworkService(Protocol):
    async def update_quote(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_quote(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_payment(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def confirm_payout(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def finalize_payout(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def complete_manual_aml_check(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NetworkServiceASGIApplication(ConnectASGIApplication[NetworkService]):
    def __init__(self, service: NetworkService | AsyncGenerator[NetworkService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.payment.NetworkService/UpdateQuote": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateQuote",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_quote,
                ),
                "/tzero.v1.payment.NetworkService/GetQuote": Endpoint.unary(
                    method=MethodInfo(
                        name="GetQuote",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_quote,
                ),
                "/tzero.v1.payment.NetworkService/CreatePayment": Endpoint.unary(
                    method=MethodInfo(
                        name="CreatePayment",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.create_payment,
                ),
                "/tzero.v1.payment.NetworkService/ConfirmPayout": Endpoint.unary(
                    method=MethodInfo(
                        name="ConfirmPayout",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.confirm_payout,
                ),
                "/tzero.v1.payment.NetworkService/FinalizePayout": Endpoint.unary(
                    method=MethodInfo(
                        name="FinalizePayout",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.finalize_payout,
                ),
                "/tzero.v1.payment.NetworkService/CompleteManualAmlCheck": Endpoint.unary(
                    method=MethodInfo(
                        name="CompleteManualAmlCheck",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.complete_manual_aml_check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment.NetworkService"


class NetworkServiceClient(ConnectClient):
    async def update_quote(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateQuote",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_quote(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetQuote",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_payment(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePayment",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def confirm_payout(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmPayout",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def finalize_payout(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FinalizePayout",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def complete_manual_aml_check(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CompleteManualAmlCheck",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class NetworkServiceSync(Protocol):
    def update_quote(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_quote(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_payment(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def confirm_payout(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def finalize_payout(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def complete_manual_aml_check(self, request: tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NetworkServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: NetworkServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.payment.NetworkService/UpdateQuote": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateQuote",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_quote,
                ),
                "/tzero.v1.payment.NetworkService/GetQuote": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetQuote",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_quote,
                ),
                "/tzero.v1.payment.NetworkService/CreatePayment": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreatePayment",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.create_payment,
                ),
                "/tzero.v1.payment.NetworkService/ConfirmPayout": EndpointSync.unary(
                    method=MethodInfo(
                        name="ConfirmPayout",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.confirm_payout,
                ),
                "/tzero.v1.payment.NetworkService/FinalizePayout": EndpointSync.unary(
                    method=MethodInfo(
                        name="FinalizePayout",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.finalize_payout,
                ),
                "/tzero.v1.payment.NetworkService/CompleteManualAmlCheck": EndpointSync.unary(
                    method=MethodInfo(
                        name="CompleteManualAmlCheck",
                        service_name="tzero.v1.payment.NetworkService",
                        input=tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckRequest,
                        output=tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.complete_manual_aml_check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment.NetworkService"


class NetworkServiceClientSync(ConnectClientSync):
    def update_quote(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateQuote",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.UpdateQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_quote(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetQuote",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.GetQuoteResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def create_payment(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePayment",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.CreatePaymentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def confirm_payout(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmPayout",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.ConfirmPayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def finalize_payout(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FinalizePayout",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.FinalizePayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def complete_manual_aml_check(
        self,
        request: tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CompleteManualAmlCheck",
                service_name="tzero.v1.payment.NetworkService",
                input=tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckRequest,
                output=tzero_dot_v1_dot_payment_dot_network__pb2.CompleteManualAmlCheckResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
