# Generated from tzero/v1/payment/provider.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .provider_pb2 import AppendLedgerEntriesRequest, AppendLedgerEntriesResponse, ApprovePaymentQuoteRequest, ApprovePaymentQuoteResponse, PayoutRequest, PayoutResponse, UpdateLimitRequest, UpdateLimitResponse, UpdatePaymentRequest, UpdatePaymentResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class ProviderService(Protocol):
    async def pay_out(self, request: PayoutRequest, ctx: RequestContext[PayoutRequest, PayoutResponse]) -> PayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_payment(self, request: UpdatePaymentRequest, ctx: RequestContext[UpdatePaymentRequest, UpdatePaymentResponse]) -> UpdatePaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_limit(self, request: UpdateLimitRequest, ctx: RequestContext[UpdateLimitRequest, UpdateLimitResponse]) -> UpdateLimitResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def append_ledger_entries(self, request: AppendLedgerEntriesRequest, ctx: RequestContext[AppendLedgerEntriesRequest, AppendLedgerEntriesResponse]) -> AppendLedgerEntriesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def approve_payment_quotes(self, request: ApprovePaymentQuoteRequest, ctx: RequestContext[ApprovePaymentQuoteRequest, ApprovePaymentQuoteResponse]) -> ApprovePaymentQuoteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ProviderServiceASGIApplication(ConnectASGIApplication[ProviderService]):
    def __init__(
        self,
        service: ProviderService | AsyncGenerator[ProviderService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.payment.ProviderService/PayOut": Endpoint.unary(
                    method=MethodInfo(
                        name="PayOut",
                        service_name="tzero.v1.payment.ProviderService",
                        input=PayoutRequest,
                        output=PayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.pay_out,
                ),
                "/tzero.v1.payment.ProviderService/UpdatePayment": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdatePayment",
                        service_name="tzero.v1.payment.ProviderService",
                        input=UpdatePaymentRequest,
                        output=UpdatePaymentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_payment,
                ),
                "/tzero.v1.payment.ProviderService/UpdateLimit": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateLimit",
                        service_name="tzero.v1.payment.ProviderService",
                        input=UpdateLimitRequest,
                        output=UpdateLimitResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_limit,
                ),
                "/tzero.v1.payment.ProviderService/AppendLedgerEntries": Endpoint.unary(
                    method=MethodInfo(
                        name="AppendLedgerEntries",
                        service_name="tzero.v1.payment.ProviderService",
                        input=AppendLedgerEntriesRequest,
                        output=AppendLedgerEntriesResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.append_ledger_entries,
                ),
                "/tzero.v1.payment.ProviderService/ApprovePaymentQuotes": Endpoint.unary(
                    method=MethodInfo(
                        name="ApprovePaymentQuotes",
                        service_name="tzero.v1.payment.ProviderService",
                        input=ApprovePaymentQuoteRequest,
                        output=ApprovePaymentQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.approve_payment_quotes,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment.ProviderService"


class ProviderServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def pay_out(
        self,
        request: PayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PayoutResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PayOut",
                service_name="tzero.v1.payment.ProviderService",
                input=PayoutRequest,
                output=PayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_payment(
        self,
        request: UpdatePaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdatePaymentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePayment",
                service_name="tzero.v1.payment.ProviderService",
                input=UpdatePaymentRequest,
                output=UpdatePaymentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_limit(
        self,
        request: UpdateLimitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateLimitResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateLimit",
                service_name="tzero.v1.payment.ProviderService",
                input=UpdateLimitRequest,
                output=UpdateLimitResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def append_ledger_entries(
        self,
        request: AppendLedgerEntriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AppendLedgerEntriesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AppendLedgerEntries",
                service_name="tzero.v1.payment.ProviderService",
                input=AppendLedgerEntriesRequest,
                output=AppendLedgerEntriesResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def approve_payment_quotes(
        self,
        request: ApprovePaymentQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ApprovePaymentQuoteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ApprovePaymentQuotes",
                service_name="tzero.v1.payment.ProviderService",
                input=ApprovePaymentQuoteRequest,
                output=ApprovePaymentQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ProviderServiceSync(Protocol):
    def pay_out(self, request: PayoutRequest, ctx: RequestContext[PayoutRequest, PayoutResponse]) -> PayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_payment(self, request: UpdatePaymentRequest, ctx: RequestContext[UpdatePaymentRequest, UpdatePaymentResponse]) -> UpdatePaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_limit(self, request: UpdateLimitRequest, ctx: RequestContext[UpdateLimitRequest, UpdateLimitResponse]) -> UpdateLimitResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def append_ledger_entries(self, request: AppendLedgerEntriesRequest, ctx: RequestContext[AppendLedgerEntriesRequest, AppendLedgerEntriesResponse]) -> AppendLedgerEntriesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def approve_payment_quotes(self, request: ApprovePaymentQuoteRequest, ctx: RequestContext[ApprovePaymentQuoteRequest, ApprovePaymentQuoteResponse]) -> ApprovePaymentQuoteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ProviderServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ProviderServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.payment.ProviderService/PayOut": EndpointSync.unary(
                    method=MethodInfo(
                        name="PayOut",
                        service_name="tzero.v1.payment.ProviderService",
                        input=PayoutRequest,
                        output=PayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.pay_out,
                ),
                "/tzero.v1.payment.ProviderService/UpdatePayment": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdatePayment",
                        service_name="tzero.v1.payment.ProviderService",
                        input=UpdatePaymentRequest,
                        output=UpdatePaymentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_payment,
                ),
                "/tzero.v1.payment.ProviderService/UpdateLimit": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateLimit",
                        service_name="tzero.v1.payment.ProviderService",
                        input=UpdateLimitRequest,
                        output=UpdateLimitResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_limit,
                ),
                "/tzero.v1.payment.ProviderService/AppendLedgerEntries": EndpointSync.unary(
                    method=MethodInfo(
                        name="AppendLedgerEntries",
                        service_name="tzero.v1.payment.ProviderService",
                        input=AppendLedgerEntriesRequest,
                        output=AppendLedgerEntriesResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.append_ledger_entries,
                ),
                "/tzero.v1.payment.ProviderService/ApprovePaymentQuotes": EndpointSync.unary(
                    method=MethodInfo(
                        name="ApprovePaymentQuotes",
                        service_name="tzero.v1.payment.ProviderService",
                        input=ApprovePaymentQuoteRequest,
                        output=ApprovePaymentQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.approve_payment_quotes,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment.ProviderService"


class ProviderServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def pay_out(
        self,
        request: PayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PayoutResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PayOut",
                service_name="tzero.v1.payment.ProviderService",
                input=PayoutRequest,
                output=PayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def update_payment(
        self,
        request: UpdatePaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdatePaymentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePayment",
                service_name="tzero.v1.payment.ProviderService",
                input=UpdatePaymentRequest,
                output=UpdatePaymentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def update_limit(
        self,
        request: UpdateLimitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateLimitResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateLimit",
                service_name="tzero.v1.payment.ProviderService",
                input=UpdateLimitRequest,
                output=UpdateLimitResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def append_ledger_entries(
        self,
        request: AppendLedgerEntriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AppendLedgerEntriesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AppendLedgerEntries",
                service_name="tzero.v1.payment.ProviderService",
                input=AppendLedgerEntriesRequest,
                output=AppendLedgerEntriesResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def approve_payment_quotes(
        self,
        request: ApprovePaymentQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ApprovePaymentQuoteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ApprovePaymentQuotes",
                service_name="tzero.v1.payment.ProviderService",
                input=ApprovePaymentQuoteRequest,
                output=ApprovePaymentQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
