# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: tzero/v1/payment/provider.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import tzero.v1.payment.provider_pb2 as tzero_dot_v1_dot_payment_dot_provider__pb2


class ProviderService(Protocol):
    async def pay_out(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_payment(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_limit(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def append_ledger_entries(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def approve_payment_quotes(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProviderServiceASGIApplication(ConnectASGIApplication[ProviderService]):
    def __init__(self, service: ProviderService | AsyncGenerator[ProviderService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.payment.ProviderService/PayOut": Endpoint.unary(
                    method=MethodInfo(
                        name="PayOut",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.pay_out,
                ),
                "/tzero.v1.payment.ProviderService/UpdatePayment": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdatePayment",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_payment,
                ),
                "/tzero.v1.payment.ProviderService/UpdateLimit": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateLimit",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_limit,
                ),
                "/tzero.v1.payment.ProviderService/AppendLedgerEntries": Endpoint.unary(
                    method=MethodInfo(
                        name="AppendLedgerEntries",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.append_ledger_entries,
                ),
                "/tzero.v1.payment.ProviderService/ApprovePaymentQuotes": Endpoint.unary(
                    method=MethodInfo(
                        name="ApprovePaymentQuotes",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.approve_payment_quotes,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment.ProviderService"


class ProviderServiceClient(ConnectClient):
    async def pay_out(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PayOut",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_payment(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePayment",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_limit(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateLimit",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def append_ledger_entries(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AppendLedgerEntries",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def approve_payment_quotes(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ApprovePaymentQuotes",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ProviderServiceSync(Protocol):
    def pay_out(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_payment(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_limit(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def append_ledger_entries(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def approve_payment_quotes(self, request: tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteRequest, ctx: RequestContext) -> tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProviderServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ProviderServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.payment.ProviderService/PayOut": EndpointSync.unary(
                    method=MethodInfo(
                        name="PayOut",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.pay_out,
                ),
                "/tzero.v1.payment.ProviderService/UpdatePayment": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdatePayment",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_payment,
                ),
                "/tzero.v1.payment.ProviderService/UpdateLimit": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateLimit",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_limit,
                ),
                "/tzero.v1.payment.ProviderService/AppendLedgerEntries": EndpointSync.unary(
                    method=MethodInfo(
                        name="AppendLedgerEntries",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.append_ledger_entries,
                ),
                "/tzero.v1.payment.ProviderService/ApprovePaymentQuotes": EndpointSync.unary(
                    method=MethodInfo(
                        name="ApprovePaymentQuotes",
                        service_name="tzero.v1.payment.ProviderService",
                        input=tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteRequest,
                        output=tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.approve_payment_quotes,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment.ProviderService"


class ProviderServiceClientSync(ConnectClientSync):
    def pay_out(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PayOut",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.PayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_payment(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePayment",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdatePaymentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_limit(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateLimit",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.UpdateLimitResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def append_ledger_entries(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AppendLedgerEntries",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.AppendLedgerEntriesResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def approve_payment_quotes(
        self,
        request: tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ApprovePaymentQuotes",
                service_name="tzero.v1.payment.ProviderService",
                input=tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteRequest,
                output=tzero_dot_v1_dot_payment_dot_provider__pb2.ApprovePaymentQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
