# Generated from tzero/v1/payment_intent/provider/provider.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .provider_pb2 import ConfirmPaymentRequest, ConfirmPaymentResponse, ConfirmPayoutRequest, ConfirmPayoutResponse, ConfirmSettlementRequest, ConfirmSettlementResponse, CreatePaymentIntentRequest, CreatePaymentIntentResponse, RejectPaymentIntentRequest, RejectPaymentIntentResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class NetworkService(Protocol):
    async def confirm_payment(self, request: ConfirmPaymentRequest, ctx: RequestContext[ConfirmPaymentRequest, ConfirmPaymentResponse]) -> ConfirmPaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def reject_payment_intent(self, request: RejectPaymentIntentRequest, ctx: RequestContext[RejectPaymentIntentRequest, RejectPaymentIntentResponse]) -> RejectPaymentIntentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def confirm_settlement(self, request: ConfirmSettlementRequest, ctx: RequestContext[ConfirmSettlementRequest, ConfirmSettlementResponse]) -> ConfirmSettlementResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class NetworkServiceASGIApplication(ConnectASGIApplication[NetworkService]):
    def __init__(
        self,
        service: NetworkService | AsyncGenerator[NetworkService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.payment_intent.provider.NetworkService/ConfirmPayment": Endpoint.unary(
                    method=MethodInfo(
                        name="ConfirmPayment",
                        service_name="tzero.v1.payment_intent.provider.NetworkService",
                        input=ConfirmPaymentRequest,
                        output=ConfirmPaymentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.confirm_payment,
                ),
                "/tzero.v1.payment_intent.provider.NetworkService/RejectPaymentIntent": Endpoint.unary(
                    method=MethodInfo(
                        name="RejectPaymentIntent",
                        service_name="tzero.v1.payment_intent.provider.NetworkService",
                        input=RejectPaymentIntentRequest,
                        output=RejectPaymentIntentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.reject_payment_intent,
                ),
                "/tzero.v1.payment_intent.provider.NetworkService/ConfirmSettlement": Endpoint.unary(
                    method=MethodInfo(
                        name="ConfirmSettlement",
                        service_name="tzero.v1.payment_intent.provider.NetworkService",
                        input=ConfirmSettlementRequest,
                        output=ConfirmSettlementResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.confirm_settlement,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment_intent.provider.NetworkService"


class NetworkServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def confirm_payment(
        self,
        request: ConfirmPaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ConfirmPaymentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmPayment",
                service_name="tzero.v1.payment_intent.provider.NetworkService",
                input=ConfirmPaymentRequest,
                output=ConfirmPaymentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def reject_payment_intent(
        self,
        request: RejectPaymentIntentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> RejectPaymentIntentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RejectPaymentIntent",
                service_name="tzero.v1.payment_intent.provider.NetworkService",
                input=RejectPaymentIntentRequest,
                output=RejectPaymentIntentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def confirm_settlement(
        self,
        request: ConfirmSettlementRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ConfirmSettlementResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmSettlement",
                service_name="tzero.v1.payment_intent.provider.NetworkService",
                input=ConfirmSettlementRequest,
                output=ConfirmSettlementResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class NetworkServiceSync(Protocol):
    def confirm_payment(self, request: ConfirmPaymentRequest, ctx: RequestContext[ConfirmPaymentRequest, ConfirmPaymentResponse]) -> ConfirmPaymentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def reject_payment_intent(self, request: RejectPaymentIntentRequest, ctx: RequestContext[RejectPaymentIntentRequest, RejectPaymentIntentResponse]) -> RejectPaymentIntentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def confirm_settlement(self, request: ConfirmSettlementRequest, ctx: RequestContext[ConfirmSettlementRequest, ConfirmSettlementResponse]) -> ConfirmSettlementResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class NetworkServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: NetworkServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.payment_intent.provider.NetworkService/ConfirmPayment": EndpointSync.unary(
                    method=MethodInfo(
                        name="ConfirmPayment",
                        service_name="tzero.v1.payment_intent.provider.NetworkService",
                        input=ConfirmPaymentRequest,
                        output=ConfirmPaymentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.confirm_payment,
                ),
                "/tzero.v1.payment_intent.provider.NetworkService/RejectPaymentIntent": EndpointSync.unary(
                    method=MethodInfo(
                        name="RejectPaymentIntent",
                        service_name="tzero.v1.payment_intent.provider.NetworkService",
                        input=RejectPaymentIntentRequest,
                        output=RejectPaymentIntentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.reject_payment_intent,
                ),
                "/tzero.v1.payment_intent.provider.NetworkService/ConfirmSettlement": EndpointSync.unary(
                    method=MethodInfo(
                        name="ConfirmSettlement",
                        service_name="tzero.v1.payment_intent.provider.NetworkService",
                        input=ConfirmSettlementRequest,
                        output=ConfirmSettlementResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.confirm_settlement,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment_intent.provider.NetworkService"


class NetworkServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def confirm_payment(
        self,
        request: ConfirmPaymentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ConfirmPaymentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmPayment",
                service_name="tzero.v1.payment_intent.provider.NetworkService",
                input=ConfirmPaymentRequest,
                output=ConfirmPaymentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def reject_payment_intent(
        self,
        request: RejectPaymentIntentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> RejectPaymentIntentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RejectPaymentIntent",
                service_name="tzero.v1.payment_intent.provider.NetworkService",
                input=RejectPaymentIntentRequest,
                output=RejectPaymentIntentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def confirm_settlement(
        self,
        request: ConfirmSettlementRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ConfirmSettlementResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmSettlement",
                service_name="tzero.v1.payment_intent.provider.NetworkService",
                input=ConfirmSettlementRequest,
                output=ConfirmSettlementResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
class ProviderService(Protocol):
    async def create_payment_intent(self, request: CreatePaymentIntentRequest, ctx: RequestContext[CreatePaymentIntentRequest, CreatePaymentIntentResponse]) -> CreatePaymentIntentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def confirm_payout(self, request: ConfirmPayoutRequest, ctx: RequestContext[ConfirmPayoutRequest, ConfirmPayoutResponse]) -> ConfirmPayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ProviderServiceASGIApplication(ConnectASGIApplication[ProviderService]):
    def __init__(
        self,
        service: ProviderService | AsyncGenerator[ProviderService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.payment_intent.provider.ProviderService/CreatePaymentIntent": Endpoint.unary(
                    method=MethodInfo(
                        name="CreatePaymentIntent",
                        service_name="tzero.v1.payment_intent.provider.ProviderService",
                        input=CreatePaymentIntentRequest,
                        output=CreatePaymentIntentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.create_payment_intent,
                ),
                "/tzero.v1.payment_intent.provider.ProviderService/ConfirmPayout": Endpoint.unary(
                    method=MethodInfo(
                        name="ConfirmPayout",
                        service_name="tzero.v1.payment_intent.provider.ProviderService",
                        input=ConfirmPayoutRequest,
                        output=ConfirmPayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.confirm_payout,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment_intent.provider.ProviderService"


class ProviderServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def create_payment_intent(
        self,
        request: CreatePaymentIntentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreatePaymentIntentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePaymentIntent",
                service_name="tzero.v1.payment_intent.provider.ProviderService",
                input=CreatePaymentIntentRequest,
                output=CreatePaymentIntentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def confirm_payout(
        self,
        request: ConfirmPayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ConfirmPayoutResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmPayout",
                service_name="tzero.v1.payment_intent.provider.ProviderService",
                input=ConfirmPayoutRequest,
                output=ConfirmPayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ProviderServiceSync(Protocol):
    def create_payment_intent(self, request: CreatePaymentIntentRequest, ctx: RequestContext[CreatePaymentIntentRequest, CreatePaymentIntentResponse]) -> CreatePaymentIntentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def confirm_payout(self, request: ConfirmPayoutRequest, ctx: RequestContext[ConfirmPayoutRequest, ConfirmPayoutResponse]) -> ConfirmPayoutResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ProviderServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ProviderServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.payment_intent.provider.ProviderService/CreatePaymentIntent": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreatePaymentIntent",
                        service_name="tzero.v1.payment_intent.provider.ProviderService",
                        input=CreatePaymentIntentRequest,
                        output=CreatePaymentIntentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.create_payment_intent,
                ),
                "/tzero.v1.payment_intent.provider.ProviderService/ConfirmPayout": EndpointSync.unary(
                    method=MethodInfo(
                        name="ConfirmPayout",
                        service_name="tzero.v1.payment_intent.provider.ProviderService",
                        input=ConfirmPayoutRequest,
                        output=ConfirmPayoutResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.confirm_payout,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.payment_intent.provider.ProviderService"


class ProviderServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def create_payment_intent(
        self,
        request: CreatePaymentIntentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreatePaymentIntentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePaymentIntent",
                service_name="tzero.v1.payment_intent.provider.ProviderService",
                input=CreatePaymentIntentRequest,
                output=CreatePaymentIntentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def confirm_payout(
        self,
        request: ConfirmPayoutRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ConfirmPayoutResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ConfirmPayout",
                service_name="tzero.v1.payment_intent.provider.ProviderService",
                input=ConfirmPayoutRequest,
                output=ConfirmPayoutResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
