name: CI / C#

on:
  push:
    branches: [master]
    paths:
      - "csharp/**"
      - "go/**"
      - "proto/**"
      - "cross_test/**"
      - ".github/actions/setup-go-helper/**"
      - ".github/actions/test-csharp/**"
      - ".github/workflows/ci-csharp.yaml"
  pull_request:
    branches: [master]
    paths:
      - "csharp/**"
      - "go/**"
      - "proto/**"
      - "cross_test/**"
      - ".github/actions/setup-go-helper/**"
      - ".github/actions/test-csharp/**"
      - ".github/workflows/ci-csharp.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  csharp:
    name: C#
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          show-progress: false

      - uses: ./.github/actions/test-csharp
