name: CI / Java

on:
  push:
    branches: [master]
    paths:
      - "java/**"
      - "proto/**"
      - "cross_test/**"
      - "go/**"
      - ".github/actions/setup-go-helper/**"
      - ".github/actions/test-java/**"
      - ".github/workflows/ci-java.yaml"
  pull_request:
    branches: [master]
    paths:
      - "java/**"
      - "proto/**"
      - "cross_test/**"
      - "go/**"
      - ".github/actions/setup-go-helper/**"
      - ".github/actions/test-java/**"
      - ".github/workflows/ci-java.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  java:
    name: Java
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: ./.github/actions/test-java
