name: Sync CLI

on:
  push:
    branches: [master]
    paths:
      - "cli/**"
      - "!cli/config.go"
      - "!cli/generate.go"
      - "!cli/install.sh"
      - "!cli/install.ps1"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.CI_APP_CLIENT_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: usdt-pay-sdk

      - uses: wadackel/files-sync-action@v3
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          config_file: .github/workflows/cli-sync-config/usdt-pay-sdk.yaml
